services:
  # Node.js application service
  app:
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: "mongodb://mongo/argentBankDB" # Use the service name 'mongo' as the hostname

  # MongoDB service
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Service Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  mongo-data:
