services:
  # Node.js application service
  app:
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: "${DATABASE_URL}"

  # MongoDB service
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Service Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development
    depends_on:
      - app

volumes:
  mongo-data:
